import sys
import os
import importlib

def test_example_2_generates_files(tmp_path, monkeypatch):
    """
    Run example_2 and verify that HTML and CSS files are generated.
    Works on Windows, pytest, without touching system PATH.
    """

    
    monkeypatch.chdir(tmp_path)

    
    
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    sys.path.insert(0, project_root)

    
    example_module = importlib.import_module("examples.example_2.script_example_2")

    
    html_file = tmp_path / "index.html"
    css_file = tmp_path / "style.css"

    
    assert html_file.exists(), "HTML file was not generated by example_2"
    assert css_file.exists(), "CSS file was not generated by example_2"

    
    html_content = html_file.read_text(encoding="utf-8")
    css_content = css_file.read_text(encoding="utf-8")

    assert "<!DOCTYPE html>" in html_content
    assert "Stylesheet generated by PyFrontKit" in css_content
